# SPRING CONFIGURATIONS
spring.application.name=@project.artifactId@
spring.application.version=@project.version@
spring.application.base-path-to-scan=com.huntercodexs
spring.main.allow-bean-definition-overriding=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
server.error.whitelabel.enabled=false

# APP INFO CONFIGURATIONS
info.app.name=@project.artifactId@
info.app.description=This service is responsible for the management of Business Groups.
info.app.version=@project.version@

# SERVICE BUS CONFIGURATIONS
# Use 'true' to enable the service bus integration or 'false' to disable it (in tests).
servicebus.enabled=false
