# SPRING CONFIGURATIONS
spring.application.name=@project.artifactId@
spring.application.version=@project.version@
spring.application.base-path-to-scan=com.huntercodexs
spring.main.allow-bean-definition-overriding=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
server.error.whitelabel.enabled=false

# APP INFO CONFIGURATIONS
info.app.name=@project.artifactId@
info.app.description=This service is responsible for the management of Business Groups.
info.app.version=@project.version@

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=123@Mudar!
spring.data.redis.timeout=1000
spring.data.redis.ssl.enabled=false

# RATE LIMITING CONFIGURATIONS
rate-limit-service-bus.enabled=true
rate-limit-service-bus.limit=10
rate-limit-service-bus.duration=50
# seconds, minutes, hours
rate-limit-service-bus.unit=minutes
rate-limit-service-bus.cache-prefix=ratelimit-service-bus-prefix-sample
rate-limit-service-bus.key-parameter=message
